version: "3.7"
services:
  # Web Server
  server-web:
    build:
      dockerfile: ./Dockerfile
      context: .
    restart: always
    volumes:
      - "../codebase/:/var/www/html"
    ports:
      - "8081:80"
  # MySQL Database
  server-mysql:
    image: mysql:8.0.19
    restart: always #always estart container on failure
    environment:
      MYSQL_ROOT_PASSWORD: "my12*uitsa&"
    volumes:
      - mysql-data:/var/lib/mysql
  # Optional MySQL Management Tool
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: server-mysql #connect to the mysql service
      PMA_USER: root
      PMA_PASSWORD: my12*uitsa&
    ports:
      - "3333:80"
volumes:
  mysql-data:
