FROM php:8.1.3RC1-apache-buster

RUN docker-php-ext-install mysqli pdo pdo_mysql 
#docker-php-ext-install is a script provided by the base PHP image to simplify the process of installing PHP extensions.
